#!/bin/csh
~/SU/bin/ftnstrip <fort.20 >20.su
~/SU/bin/ftnstrip <fort.21 >21.su
~/SU/bin/ftnstrip <fort.22 >22.su

~/SU/bin/ximage n1=$1 <20.su wbox=2050 hbox=1420 cmap=hue legend=1 d1=6.25 d2=6.25
~/SU/bin/ximage n1=$1 <20.su wbox=2050 hbox=1420 legend=1 d1=6.25 d2=6.25

#~/SU/bin/ximage n1=$1 <21.su wbox=800 hbox=280 cmap=hue legend=1
#~/SU/bin/ximage n1=$1 <22.su wbox=800 hbox=280 cmap=hue legend=1

~/SU/bin/psimage n1=$1 <20.su style=normal label1="Depth"  title="Dablain Model" units="meters/second" bps=24 xbox=2.2 lx=1.0 ybox=1.5 width=5.5 height=8.5 wrgb=0.0,0,1.0 grgb=0.5,0.0,0.5 brgb=1.0,0,0.0 threecolor=1 legend=1 >modelcolor.ps

~/SU/bin/psimage n1=$1 <20.su style=normal label1="Depth"  title="Dablain Model" units="meters/second"  bps=24 xbox=2.2 lx=1.0 ybox=1.5 width=5.5 height=8.5  legend=1 >modelgrey.ps

~/SU/bin/psimage n1=$1 <21.su  legend=1 >21.ps
~/SU/bin/psimage n1=$1 <22.su  legend=1 >22.ps

#lp 20.ps
#lp 21.ps
#lp 22.ps
##ps2pdf  modelcolor.ps
##ps2pdf  modelgrey.ps

